### ISSUE TITLE
Error when using !vis command.

### ISSUE THREAD

**Issue by Spookats** [AoDude/RuneInfo#20]
![2017-08-23 13_23_57- bot-spam - discord](https://user-images.githubusercontent.com/31279019/29615595-6816b446-8806-11e7-9bdb-714fdd14c3e8.png)

**Comment by AoDude** [comment]
This is because viswax fc has a malformed date in their post:
![img](https://puu.sh/xh46w/772e42dee4.png)

That line matches the date, and extracts the number. However since there is no match (because 23rdd; is not valid) there is no match to extract the number from. I have spoken with viswax fc several times in the past to help move them to something more consistent, like google sheets. (where it would be easy to validate fields) But that hasn't happened to my knowledge. (it would also help with the blank entries, because for some reason they like to edit the combo in stages, instead of all at once)

This is one of those things where if I fix it today, to their incorrect date format, it will just break again tomorrow when they go back to using a valid format. So unless you want to reach out to viswax fc, there isn't much that can be done. (I haven't been in game much at all for months now)
