### ISSUE TITLE
Automatic Deletion

### ISSUE THREAD

**Issue by Erebea** [AoDude/RuneInfo#4]
It'd be really great if there was a function that automatically deleted the bot's output along with the relevant command after a certain amount of time. The most frequently used commands output messages that cover nearly the entire chatbox.

**Comment by bdistin** [comment]
This would be possible, but I am unlikely to do so for a couple reasons:

This would make the commands require "Manage Messages" permission to be run. (Right now the only command that requires that is `!pinhelp`) After 500 guilds, I am not sure it is right of me to demand this new permission to use all commands without lots of support for this change.

This would likely cause people to run the commands more often than done currently, causing unnecessary hits to all of the APIs that I use. Take for instance `!penglocs` command. It takes a while for you to work through that list, and it really isn't going to change while you are working through the list. If it were to disappear (do to auto delete) before they are done, they would have to run the command again, which would make RuneInfo hit the penguin api again. In the long term that will be unsustainable due to varying API rate-limits across the services RuneInfo gets its information (with the ever increasing amount of guilds and command usage).

Now if you had/were using a moderation bot to purge the channel, then there is nothing I can do to prevent that. And if that is the way you want to manage your guild, then I encourage you to do that. 

That is my opinion, I will leave this issue open to see if this request gets more support.

**Comment by AoDude** [comment]
This is possible, but I am unlikely to do so for a couple reasons:

This would require a lot of commands to require the "Manage Messages" permission. Currently the only command that requires it is `!pinhelp` and is very much optional. After 500 guilds, I don't feel it is fair to require a previously optional permission, unless there was huge support for this request.

This would likely increase the number of API requests the bot makes unnecessarily. Things like `!penglocs` would not be able to be completed in game before the message would likely need to be deleted, which would mean they would have to issue the command again which would be another hit against that respective API. This is unsustainable due to varying rate-limits across the many APIs RuneInfo uses, and the ever growing number of guilds and command usage.

If you want to manage your guild as you have described, I suggest using a moderation bot to purge the commands and RuneInfo's responses. However I will leave this issue up for it to gain support and or feedback.

**Comment by AoDude** [comment]
It's been 9 months since this suggestion with no further support, so I am closing this issue. Thanks for the suggestion.
