### ISSUE TITLE
!wiki issue

### ISSUE THREAD

**Issue by DDot** [AoDude/RuneInfo#64]
!wiki shows wrong info for Inquisitor staff

![Discord_2020-04-21_11-00-31](https://user-images.githubusercontent.com/693550/79830752-85806d80-83bf-11ea-9927-aff48f3a099b.png)

**Comment by AoDude** [comment]
The wiki shows results as provided by the wiki api. They appear to be sorted by most popular pages for the search term, and since the page is relatively new, it's not very popular yet. The issue will sort itself over time as the wiki software learns what's more relevant for that search result. This isn't something I can fix on my side. Check page 8 as of earlier today.
