### ISSUE TITLE
Website Down and Bot Down?

### ISSUE THREAD

**Issue by Dgoss16** [AoDude/RuneInfo#65]
Not able to reach the website and the bot no longer works in my dis channel

**Comment by MrRaymondX** [comment]
Correct, the ISP of RuneInfo is having some trouble rewiring thier building. 
If you join the RuneInfo discord channel you can get more info, but that's optional.

**Comment by AoDude** [comment]
The building where the bot and website are being hosted is being completely re-fibered by the ISP (due to issues experienced earlier in the year with mice chewing on exposed fiber lines). While this was supposed to be a two day job (last thursday/friday) there have been a number of hurdles further delaying my specific fiber line (as well as others in the same building). Today I was informed that the subcontractor made all of the fiber runs 6' too short (~2 meters), and the splice tech ran out of fiber on his spool while trying to make up for all the short runs. The splice tech is supposed to be on another job tomorrow, so he was unsure if he would be able to return tomorrow to finish or if it would be Monday before he can return. I apologize for the down time, but there isn't anything I can do about it at this time.

For further updates, please join the official discord via the link in the readme.
